/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
  theme: {
    colors: {
      'white': "#FFFFFF",
    },
    extend: {
      width: {
        "5vw": "5vw",
        "10vw": "10vw",
        "15vw": "15vw",
        "20vw": "20vw",
        "25vw": "25vw",
        "30vw": "30vw",
        "35vw": "35vw",
        "40vw": "40vw",
        "45vw": "45vw",
        "50vw": "50vw",
        "55vw": "55vw",
        "60vw": "60vw",
        "65vw": "65vw",
        "70vw": "70vw",
        "75vw": "75vw",
        "80vw": "80vw",
        "85vw": "85vw",
        "90vw": "90vw",
        "95vw": "95vw",
        "100vw": "100vw",
        "5vh": "5vh",
        "10vh": "10vh",
        "15vh": "15vh",
        "20vh": "20vh",
        "25vh": "25vh",
        "30vh": "30vh",
        "35vh": "35vh",
        "40vh": "40vh",
        "45vh": "45vh",
        "50vh": "50vh",
        "55vh": "55vh",
        "60vh": "60vh",
        "65vh": "65vh",
        "70vh": "70vh",
        "75vh": "75vh",
        "80vh": "80vh",
        "85vh": "85vh",
        "90vh": "90vh",
        "95vh": "95vh",
        "100vh": "100vh",
      },
      height: {
        "5vh": "5vh",
        "10vh": "10vh",
        "15vh": "15vh",
        "20vh": "20vh",
        "25vh": "25vh",
        "30vh": "30vh",
        "35vh": "35vh",
        "40vh": "40vh",
        "45vh": "45vh",
        "50vh": "50vh",
        "55vh": "55vh",
        "60vh": "60vh",
        "65vh": "65vh",
        "70vh": "70vh",
        "75vh": "75vh",
        "80vh": "80vh",
        "85vh": "85vh",
        "90vh": "90vh",
        "95vh": "95vh",
        "100vh": "100vh",
        "5vw": "5vw",
        "10vw": "10vw",
        "15vw": "15vw",
        "20vw": "20vw",
        "25vw": "25vw",
        "30vw": "30vw",
        "35vw": "35vw",
        "40vw": "40vw",
        "45vw": "45vw",
        "50vw": "50vw",
        "55vw": "55vw",
        "60vw": "60vw",
        "65vw": "65vw",
        "70vw": "70vw",
        "75vw": "75vw",
        "80vw": "80vw",
        "85vw": "85vw",
        "90vw": "90vw",
        "95vw": "95vw",
        "100vw": "100vw",
      },
      
      colors: {
        "rich-black": "#0B0D17",
        periwinkle: "#D0D6F9",
        white: "#FFFFFF",
      },
      fontFamily: {
        bellefair: ["Bellefair", "serif"],
        barlow: ["Barlow Condensed", "sans-serif"],
      },
      backgroundImage: {
        "home-lg": "url('/assets/home/background-home-desktop.jpg')",
        "home-md": "url('/assets/home/background-home-tablet.jpg')",
        "home-sm": "url('/assets/home/background-home-mobile.jpg')",
        "destination-lg":
          "url('/assets/destination/background-destination-desktop.jpg')",
        "destination-md":
          "url('/assets/destination/background-destination-tablet.jpg')",
        "destination-sm":
          "url('/assets/destination/background-destination-mobile.jpg')",
        "crew-lg": "url('/assets/crew/background-crew-desktop.jpg')",
        "crew-md": "url('/assets/crew/background-crew-tablet.jpg')",
        "crew-sm": "url('/assets/crew/background-crew-mobile.jpg')",
        "technology-lg":
          "url('/assets/technology/background-technology-desktop.jpg')",
        "technology-md":
          "url('/assets/technology/background-technology-tablet.jpg')",
        "technology-sm":
          "url('/assets/technology/background-technology-mobile.jpg')",
      },
    },
  },
  plugins: [],
};
